### ISSUE TITLE
Dash in task names not allowed

### ISSUE THREAD

**Issue by proski** [JamesFrost/SimpleDo#1]
What's wrong with calling Jean-Jacques or buying tickets to Stratford-upon-Avon? Funny enough, I can create tasks in Russian, so Unicode must be supported, but a standard ASCII symbol is not allowed.

**Comment by JamesFrost** [comment]
The dash character is reserved due to how task names are processed and read; the dash is part of how the program expects names to be formatted.

**Comment by proski** [comment]
SimpleDo is a small app with few features, yet it suffers from a problem typical to old software - data structures are inadequate to the task. No way to keep formatting separate from the data? No better candidates for a formatting symbol among the 1114111 Unicode codepoints? If it's unfixable today, it won't be fixable a year from now. Whatever.

**Comment by JamesFrost** [comment]
I hadn't thought about using a Unicode symbol as the separator. You can now use a dash in task names. This will be included in the next release. b02b96ad4900a9c12e35fd4412b279a8f90ca683

**Comment by proski** [comment]
Thank you!
